version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.9.6-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.kokos.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        # external_url 'https://gitlab.kokos.com'
    ports:
      - '8929:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    
